- op: replace
  path: /spec/template/spec/containers/name=nextcloud/volumeMounts/name=nextcloud-name/mountPath
  value: /foo
- op: replace
  path: /spec/template/spec/containers/name=nextcloud-cron/volumeMounts/name=nextcloud-name/mountPath
  value: /foo