apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          volumeMounts:
            - mountPath: /var/www/html/data
              name: nfs-data
        - name: nextcloud-cron
          volumeMounts:
            - mountPath: /var/www/html/data
              name: nfs-data